name: Deploy

on:
  workflow_dispatch:
    inputs:
      ENVIROMENT:
        description: "environment: the target environment where to execute the validatation or deployment"
        type: environment
        required: true

jobs:
  builda:
    environment:
      name: ${{ github.event.inputs.ENVIROMENT }}
    runs-on: ubuntu-latest

    steps:
      - name: build
        run: echo Hello, world!

  deploy:
    runs-on: ubuntu-latest
    needs: [builda]
    steps:
      - name: deploy
        run: echo Hello, world!
