name: Deploy

on:
  workflow_dispatch:
    inputs:
      ENVIROMENT:
        description: "environment: the target environment where to execute the validatation or deployment"
        required: true

jobs:
  deploy:
    environment:
      name: ${{ github.event.inputs.ENVIROMENT }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo ${{ secrets.MY_SECRET }} >> secrets.txt
          cat secrets.txt
